Month7/step2
gvozdenkov/stellar-burgers pull request #2
Opened 2023-04-03 15:15 UTC by gvozdenkov

2023-04-03 19:26 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Классная анимация
- Хорошая декомпозиция компонентов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Есть ошибка в консоли
 <img width="500" alt="Снимок экрана 2023-04-03 в 22 06 08" src="https://user-images.githubusercontent.com/60173362/229603204-817b48e6-f664-4830-b682-843a47aaae08.png">

- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер
- У некоторых компонентов, например `MenuItem` не хватает `isRequired` в `propTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- Добавьте возможность закрытия модалки по клавише `ESC`

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-03 19:26 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +    {
**Можно лучше**
Тут можно обойтись уже без моковых данных

2023-04-04 08:06 UTC, gvozdenkov commented
Не совсем понял про обязательные пропсы для `MenuItem`. Там только один обязательный - текстовое название меню. Картинка опциональная, состояние active тоже опционально - оно задаётся по дефолту.

2023-04-04 09:32 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-04 09:32 UTC, andryxxa93 commented
> Не совсем понял про обязательные пропсы для `MenuItem`. Там только один обязательный - текстовое название меню. Картинка опциональная, состояние active тоже опционально - оно задаётся по дефолту.

Да, в таком случае это не обязательно.

2023-04-04 09:46 UTC, merged